name: holo_mobile
description: Holo Mobile Flutter application
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  logger: ^2.4.0
  get_it: ^8.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
